feat: Add Content Security Policies
freedomofpress/pressfreedomtracker.us pull request #1046
Opened 2021-05-02 09:58 UTC by prateekj117

Adds Content Security Policies similar to [securedrop.org](https://github.com/freedomofpress/securedrop.org/blob/develop/securedrop/settings/base.py#L313-L367) and [securethenews](https://github.com/freedomofpress/securethenews/blob/develop/securethenews/settings/base.py#L251-L303).

2021-05-02 10:02 UTC, prateekj117 commented
@SaptakS I know `unsafe-inline` in `script-src` and `style-src` is the worst way to go, but these are required for Wagtail Admin. I can be more explicit though in these policies and ignore `unsafe-inline`, but I see in CSP rules of [securethenews](https://github.com/freedomofpress/securethenews/blob/develop/securethenews/settings/base.py#L251-L303) as well, we went this way. Let me know if you want me to be more explicit.

2021-05-02 12:01 UTC, SaptakS commented
Yes. For Wagtail Admin, for now, we have to include unsafe-inline. All forms have inline scripts. There is an RFC by wagtail which is meant to fix this issue but not anytime soon, so that is fine for now. I will check the rest of the code.

2021-05-03 12:13 UTC, SaptakS requested changes
Thanks for the PR!!! I have left few comments mostly related to updates that we needed previously in other repos. Please let me know if you feel otherwise.

Also, there are certain pages in tracker website where we use data vizualisation which needs to allow other script and style src probably. I know @harrislapiroff is working on data viz so maybe he can let you know what are the CSP rules that need to be updated.

2021-05-03 12:13 UTC, SaptakS commented on tracker/settings/base.py
> +    "analytics.freedom.press",
Please add `https://` here

2021-05-03 12:13 UTC, SaptakS commented on tracker/settings/base.py
> +    "http://www.gravatar.com",
You can remove this. This just adds the default gravatar in the admin section, which we don't care about, so doesn't make sense adding an entirely new src in CSP rules for just that.

2021-05-03 12:13 UTC, SaptakS commented on tracker/settings/base.py
You will also need to set a section like this: https://github.com/freedomofpress/securedrop.org/blob/develop/securedrop/settings/base.py#L353-L361. Some of the CSP rules are set at the deployment time with environment variables. As part of that, you need to add a `CSP_OBJECT_SRC` with self for certain PDFs, etc.

2021-05-03 12:13 UTC, SaptakS commented on tracker/settings/base.py
You can actually just add a section like:

```
if os.environ.get("DJANGO_CSP_MEDIA_ORIGINS"):
    csp_media_origins = os.environ["DJANGO_CSP_MEDIA_ORIGINS"].split()
    CSP_MEDIA_SRC.extend(csp_media_origins)  # video files
    CSP_IMG_SRC.extend(csp_media_origins)
    CSP_OBJECT_SRC.extend(csp_media_origins)
    CSP_CONNECT_SRC.extend(csp_media_origins)
```

2021-05-03 12:13 UTC, SaptakS commented on tracker/settings/base.py
> +)
With previous experience in other repos, I think you will need:

```
# Embeds
    'https://platform.twitter.com',  # Twitter
    'https://syndication.twitter.com',  # Twitter
    'https://pbs.twimg.com',  # Twitter
    'https://ton.twimg.com',  # Twitter
    'data:',  # Twitter makes use of data svgs
```
to be added to CSP_IMG_SRC to allow twitter images.

2021-05-06 19:39 UTC, SaptakS requested changes
There are few more things that need to be added for everything to work.

SCRIPT_SRC:
- 'https://www.google.com/recaptcha/',
- 'https://www.gstatic.com/recaptcha/',
- 'https://cdn.jsdelivr.net',  # Observable Notebooks
- 'https://api.observablehq.com',  # Observable Notebooks
- 'https://bundle.run',  # Observable Notebooks

CONNECT_SRC:
- 'https://cdn.jsdelivr.net',  # Observable Notebooks
- 'https://pressfreedomtracker.us',  # Observable Notebooks

Also, please rebase the PR. After that, this should be ready for merging.

2021-05-08 10:46 UTC, prateekj117 commented
@SaptakS Done.

2021-05-12 14:22 UTC, SaptakS approved these changes
Looks good to me.

2021-05-25 15:37 UTC, merged