Incident cards
freedomofpress/pressfreedomtracker.us pull request #1179
Opened 2021-12-15 21:42 UTC by chigby

Refs #1173

2021-12-16 09:50 UTC, SaptakS commented
Updated the base to point to `redesign` instead of `develop`

2021-12-20 23:03 UTC, chigby commented
@SaptakS This is ready for review except for the failing test :sweat_smile: I'll figure out what's going on with that tomorrow, but the rest of the code is in a good spot I think.

2021-12-21 14:18 UTC, SaptakS requested changes
This looks good! I like that the width is kept fluid, so we can design that based on the parent element. Left a few comments, mostly some HTML semantic stuff.

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +		<h1 class="card-title-{{ size }}">{{ incident.title }}</h1>
Every HTML page should ideally have only 1 `<h1>` tag usually reserved for the page title. That helps in maintaining the structure of the page such that page title is h1, then all sub-sections have h2, and then anything inside that have h3-h6. So given how most templates look, I will recommend using `<h3>` here. Some heading best practices are mentioned here: https://accessibility.psu.edu/headingshtml/

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +	<div class="incident-card">
Though I don't have super strong opinion here, but I feel [`<article>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) gives a better semantic meaning. Thought?

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +		<ol>
Are the categories in some specific order for incidents? I remember that each incident has like a main category or something. In that case, maybe makes sense if that's the first category shown. Else maybe we want to use `<ul>` instead?

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +				{{ incident.latest_update|date:"F j, Y" }}
It might be good to wrap this in [`<time>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time). So something like:
```html
<dd>
  <time datetime="{{ incident.latest_update|date:"c" }}">
    {{ incident.latest_update|date:"F j, Y" }}
  </time>
</dd>
```

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +			<dd>{{ incident.date|date:"F j, Y" }}</dd>
Same as above.

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +					<li><a href="#" class="btn btn-tag">#{{ tag.title }}</a></li>
Just noting here that the href is a TODO to be added once we add urls and pages for individual tags.

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_index_page.html
> +	{% endfor %}
I know this page's entire design implementation is far from finished, so I am okay merging this for now, but I think later, we should ensure a `<ul>`/`<ol>` structure depending on whether its sorted by certain attribute, or whether it's a curated list.

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +		<h1 class="card-title-{{ size }}">{{ incident.title }}</h1>
Also, I think based on the design, at least the heading part should be inside `<a>` tags pointing to the particular incident page. I am mostly neutral about whether the entire card should be inside an `<a>` tag (slightly more inclined towards no). Also given the design, the anchor tag under `.incident-card` will have slightly different design (`text-decoration: none` in beginning and `underline` on `:hover`. And unlike the default link style, `background-color: transparent` on `:hover`.

The hover styles and focus styles are the cards below the first card shown in the design respectively. Unless we do `<a>` on entire card, the focus style is messy to attain. But I am personally okay if the focus style applies only to the heading text (which it automatically will based on default `<a>`). @harrislapiroff @chigby do you have any strong preferences?

2021-12-21 14:18 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +	<div class="incident-card">
Also all the incident cards have a border line at the top. I think can be attained by adding a `border-top: 1px solid; border-color: $black;`

2021-12-21 17:17 UTC, chigby commented on incident/templates/incident/incident_card.html
> +		<ol>
The first category being the "main" category was what motivated putting these in an `<ol>`, but the more I think about it, that might not be the best way of representing that idea.

2021-12-21 17:30 UTC, chigby commented on incident/templates/incident/incident_card.html
> +		<h1 class="card-title-{{ size }}">{{ incident.title }}</h1>
Thanks for pointing out the hover/focus styles, I completely missed that. Though one thing I'm seeing is that the `<a>` tag has a default font size that's taking precedence over the `card-title-{big,small}` typography styles. How do you think we should address that?

2021-12-21 17:30 UTC, chigby commented on incident/templates/incident/incident_card.html
> +				{{ incident.latest_update|date:"F j, Y" }}
Updated this PR with the time tags. Great idea!

2021-12-21 17:31 UTC, chigby commented on incident/templates/incident/incident_card.html
> +	<div class="incident-card">
Added both of these to the PR.

2021-12-21 17:39 UTC, chigby commented on incident/templates/incident/incident_card.html
> +		<h1 class="card-title-{{ size }}">{{ incident.title }}</h1>
I guess maybe the class could be applied to the `<a>` instead?

2021-12-21 17:57 UTC, SaptakS commented on incident/templates/incident/incident_card.html
> +		<ol>
But I think it's okay to leave it `<ol>` then given there is some order. So let's keep it that way.

2021-12-21 18:53 UTC, chigby commented on incident/templates/incident/incident_card.html
> +		<h1 class="card-title-{{ size }}">{{ incident.title }}</h1>
After some discussion, also added the hover styles into the PR.

2021-12-21 19:21 UTC, chigby commented
Should be ready for re-review and/or merging.

2021-12-22 13:55 UTC, SaptakS commented
All looks good to me. Only I think the article cards need a padding-top of 2rem based on the design. Also the link class needs a display: inline-block so that border in the :focus shows correctly. After that, this should be good to merge

2021-12-22 15:53 UTC, chigby commented
Added those

2021-12-22 16:16 UTC, SaptakS approved these changes
Looks good to me

2021-12-22 18:03 UTC, merged