Menus
freedomofpress/pressfreedomtracker.us pull request #1182
Opened 2022-01-03 21:15 UTC by chigby

Fixes #1171 

This PR implements the mobile, tablet, and desktop top site menu as outlined in the issue/design. I've put the menu in the styleguide, as there's not really any other page to apply it to, so please go there to test it out.

Potential issues I know about:

1. There is no animation for the open/close icon changing state. Right now it just changes. I have not really looked into how to make that animation between two SVGs work, and I don't know how I'd go about it. Might be worth making into another issue.
2. The mobile/tablet menu list does not have a hover state. I was looking at the design document for this and it seems slightly tricky and like it might want to become its own component (e.g., it needs to be able to display logos on hover), so I have basically implemented the minimum necessary for this PR. Also potentially it doesn't matter since mobile/tablet interfaces don't really support a hover state (that I'm aware of).
3. The Styleguide page has horizontal scrollbars at mobile widths, which affects the menu. My assumption is that when more of the page layout code is complete this kind of thing will be prevented, so I have not attempted to provide my own slapdash fix for the Styleguide page. 
4. When the viewport is around 770-800 pixels wide, the buttons are a bit scrunched. My opinion here is we might want to think a little bit about how wide we consider a "tablet" for the purposes of our media queries. According to Firefox, the iPad's effective pixel width is 810 pixels, and right now that width is being shown the "desktop" layout (smaller than this and the scrunch starts to occur). This could also happen if the number/size of the menu items changes (see below).

So, if you have thoughts on any of the above, or if you have feedback about the implementation markup, SASS, Javascript, please let me know. I've tried to take into account relevant attributes for assistive technologies, added a `sr-only` class that we might want to use elsewhere (I just copied it from what was on the site before), and made the "vertical wipe" animation in the simplest way I could figure out. There might be other ways though. Any and all comments welcome regarding all of this: I want these foundational elements to be the best they can be.

Open question:

Are the menu items intended to be hard-coded or loaded from Wagtail settings? They are hard-coded right now, but we do have a system for allowing admins to input menu items. We would have to change that system a little bit, I think, to incorporate the ideas of "primary" and "secondary" navigation.

2022-01-10 12:40 UTC, SaptakS requested changes
For the most part it looks great! Few things I noticed, in the mobile width, there seems to be an overflow and the "Go to the page" seems not visible. Are you noticing this too? I checked in Firefox. Also, in desktop mode, the "U.S. Press Freedom Tracker" seems to be wrapping for me instead of fitting in a single line.

Also, I think we need a design like [this](https://www.figma.com/proto/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3912%3A63655&scaling=min-zoom&page-id=3897%3A59348&starting-point-node-id=3897%3A59349) for the menu links in smaller screens.

2022-01-10 17:54 UTC, chigby commented
Pushed some changes to this PR to:

1. Prevent the title link from wrapping 
2. Prevent overflow on the styleguide page (which should make it so that the menu properly fits on the page on small screens and does not extend so far that the "Go to this page" is visible).

@SaptakS Do you think this PR should include a design for the menu links with extra info? Or should that be a separate PR for that version of the lists component?

2022-01-12 17:56 UTC, chigby commented
@SaptakS This is rebased now, conflicts resolved

2022-01-12 19:28 UTC, SaptakS approved these changes
Looks good to me. Let's get this merged.

2022-01-12 19:29 UTC, merged