Blog card components
freedomofpress/pressfreedomtracker.us pull request #1185
Opened 2022-01-05 20:43 UTC by chigby

This PR adds blog card components mostly based off of the model already established by the incident card components. I have added some additional helper styles for the images so that they don't end up on the same line as the card title when the width of the card is very wide (which might not happen anywhere besides the styleguide, but it's good to be prepared).

The component is demonstrated in the styleguide as well.

2022-01-10 12:08 UTC, SaptakS requested changes
Left a nitpick comment. Apart from that, I see that the blog cards are missing the top border as shown in the figma design. Also the spacing between the heading and the teaser text is a bit much. This is because of the default h3 and p spacing. So would need to adjust for this particular case, such that the space is 12px as shown in the figma designs.

2022-01-10 12:08 UTC, SaptakS commented on blog/templates/blog/blog_card.html
> +			{% endif %}
Ending tag for `<dl>` is missing.

2022-01-10 16:18 UTC, chigby commented
Rebased this (to fix safety check) and also addressed the points mentioned. Ready for another review.

2022-01-11 11:57 UTC, SaptakS approved these changes
LGTM

2022-01-11 11:59 UTC, merged