Categories block
freedomofpress/pressfreedomtracker.us pull request #1194
Opened 2022-01-12 15:28 UTC by chigby

Refs #1193

2022-01-18 11:43 UTC, SaptakS commented
I was able to achieve something of these sorts:

![image](https://user-images.githubusercontent.com/9530293/149930722-e77bc203-060f-49bd-9668-74541c8ccbc1.png)


Basically what I did was remove the `flex: 1` in the child elements which I guess you did so that each row takes up 100% space. And then to each of those elements, I added a `margin-left: -3px; margin-top: -3px` if the border width is 3px, to compensate for the double bordering. Then you can adjust the parent element's margin to compensate for the overall 3px shift to top and left. Also, the actual design being exactly same as the design would definitely depend on the order in which the categories are shown, which I think is fine. Also, you will need to add `justify-content: center` to the parent element.

2022-01-18 19:54 UTC, chigby commented
@SaptakS I put the finishing touches on this one and it's ready for review. Let me know what you think.

2022-01-19 21:28 UTC, chigby commented
Rebased this on the latest `category-symbol` branch. It's ready for review (and should be merged after that branch).

2022-01-25 08:20 UTC, SaptakS requested changes
Only one small change. After that, this can be merged

2022-01-25 08:20 UTC, SaptakS commented on client/common/sass/components/_categories-block.sass
> +.categories-block--item
This should be `&--item` instead.

2022-01-25 14:12 UTC, chigby commented on client/common/sass/components/_categories-block.sass
> +.categories-block--item
Good catch here, I've added it.

2022-01-25 14:22 UTC, SaptakS approved these changes

2022-01-25 15:21 UTC, merged