Blog details page
freedomofpress/pressfreedomtracker.us pull request #1251
Opened 2022-02-23 14:39 UTC by SaptakS

Fixes #1198 

This adds the blog details template, without the "In the Database" section. Also, fixed few JS fallbacks for the data table viewing and updated heading blocks.

2022-02-24 17:26 UTC, chigby requested changes
Requested a few changes as noted in the comments. I also opened a PR (#1254) that will, once merged and this branch rebased, will resolve the failing safety check.

Let me know if you have any questions.

2022-02-24 17:26 UTC, chigby commented on blog/templates/blog/_details_table.html
> +				</a>
Sorry that this is kind of a nitpick, but putting this value `{{ blog.author.title }}` on a line by itself is causing the link to render with extra whitespace in it and the underline extends past the end of the text (for me, anyway). I have run into this problem a fair bit myself and the simplest solution is to condense these 3 lines into a single line. If there's another way, I'd actually like to hear about it, as other than `spaceless` (which doesn't really do what we want here) Django templates don't appear to me to have the kind of fine-grained whitespace controls that allow us to preserve readable formatting as well as getting the output we want.

2022-02-24 17:26 UTC, chigby commented on blog/templates/blog/blog_page.html
> +		{% if page.introduction %}
Does the blog page model have an introduction field?

2022-02-24 17:26 UTC, chigby commented on blog/templates/blog/blog_page.html
> +			{% include 'common/_video_or_image.html' with video=page.primary_video image=page.teaser_image caption=page.image_caption %}
I am not sure this `video_or_image` component matches the design exactly, the font size is (I think) one step too large and it does not include the image attribution.

2022-02-28 06:39 UTC, SaptakS commented
@chigby addressed your comments

2022-02-28 15:27 UTC, chigby approved these changes

2022-02-28 15:28 UTC, merged