Adds chart to the category pages
freedomofpress/pressfreedomtracker.us pull request #1508
Opened 2022-10-19 09:17 UTC by SaptakS

Resolves #1479

2022-11-02 16:26 UTC, chigby requested changes

2022-11-02 16:26 UTC, chigby commented on client/common/js/categoryPage.jsx
> +			dataUrl={`/api/edge/incidents/?${params.toString()}`}
I hope the performance on this API call ends up being acceptable. I could see us having to make some similar optimizations to category-level data that we made for the home page data. :/

2022-11-02 16:26 UTC, chigby commented on common/models/pages.py
> +        context['viz_data_end'] = f"{self.viz_data_end}-12-31"
I notice we're not using `viz_type` here -- how does this field get used if we want to turn off the chart?

2022-11-02 16:26 UTC, chigby commented on common/models/pages.py
> +BIRTH_YEAR_CHOICES = ['1980', '1981', '1982']
Included by mistake? :sweat_smile:

2022-11-02 16:26 UTC, chigby commented on client/charts/sass/ChartDescription.sass
> +	margin-bottom: 1rem
THANK YOU for moving this stuff out of the Javascript :tada: It gets me a little every time I see the static CSS in there

2022-11-02 16:26 UTC, chigby commented on client/charts/js/components/TreeMap.jsx
> +					aria-labelledby={id}
I'm a big fan of this

2022-11-02 16:26 UTC, chigby commented on common/models/pages.py
> +    )
I think this is a fine start for how to structure visualization data on category pages, but I worry a little bit that it's not scalable if we ever wanted to have more than one chart on a page. Though maybe that's not something we're planning.

2022-11-02 16:26 UTC, chigby commented on common/models/pages.py
> +    )
Ok I just looked at the ticket and it says "multiple types of chart" which isn't necessarily the same as multiple charts, and which this data schema handles fine.

If we _did_ want to make it easier to add multiple charts in the future, I could actually see replacing these with a StreamField, where the different block types could correspond to the different chart types.

2022-11-02 16:27 UTC, chigby commented
Oh, I forgot to type this in the review box, but I think before this can be merged we need to be able to disable the charts. See the comment about `viz_type` -- if that's set to "none" the chart should not be rendered, right?

2022-11-02 16:45 UTC, harrislapiroff commented on client/charts/js/components/BarChartCommon.jsx
> +export default function BarChartCommon({
I think it would actually be straightforward to just call this `BarChart`

2022-11-02 16:45 UTC, harrislapiroff commented on client/charts/js/components/CategoryPageChart.jsx
> +			<div className={'cpChartContainer'} style={{ width: width }}>
I notice strings in a lot of this code (including some of the stuff I wrote) are javascript expressions. Is there a reason we're doing that that I've forgotten, or can we open an issue to clean that up? It seems weird to me.

2022-11-02 16:45 UTC, harrislapiroff commented on client/charts/js/components/BarChartCommon.jsx
> +					aria-labelledby={id}
Does this property get ignored by browsers if `id` is an empty string?

2022-11-02 17:19 UTC, SaptakS commented on client/charts/js/components/CategoryPageChart.jsx
> +			<div className={'cpChartContainer'} style={{ width: width }}>
I think we can clean it up.

2022-11-02 17:19 UTC, SaptakS commented on client/charts/js/components/BarChartCommon.jsx
> +					aria-labelledby={id}
ignored in the sense that the svg won't have an accessible name, yes.

2022-11-02 17:20 UTC, SaptakS commented on common/models/pages.py
> +BIRTH_YEAR_CHOICES = ['1980', '1981', '1982']
Yep. 😓

2022-11-02 17:20 UTC, SaptakS commented on common/models/pages.py
> +        context['viz_data_end'] = f"{self.viz_data_end}-12-31"
I was supposed to put it in the html itself for checking, and then pass it in the component. Might have missed doing that.

2022-11-02 17:21 UTC, SaptakS commented on client/common/js/categoryPage.jsx
> +			dataUrl={`/api/edge/incidents/?${params.toString()}`}
I did have a similar discussion with @harrislapiroff raising the exact same concerns so..... 🤞🏽

2022-11-02 17:31 UTC, harrislapiroff commented on client/charts/js/components/BarChartCommon.jsx
> +					aria-labelledby={id}
Just want to make sure it won't accidentally pair with some other element

2022-11-03 07:47 UTC, SaptakS commented on common/models/pages.py
> +        context['viz_data_end'] = f"{self.viz_data_end}-12-31"
I have added a check in the HTML for the same. Also, I am sending the data in JS, and checking the vizType to load the correct chart (in this case, there's only one chart type, but in future we might have multiple types to chose from)

2022-11-03 16:14 UTC, chigby approved these changes

2022-11-03 16:15 UTC, chigby commented
Changes look good to me. @harrislapiroff do you think we should merge it?

2022-11-03 16:37 UTC, harrislapiroff commented
LGTM!

2022-11-03 16:37 UTC, merged