Templates for newsletter and special blog posts
freedomofpress/pressfreedomtracker.us pull request #1595
Opened 2023-03-20 14:45 UTC by SaptakS

Fixes #1480 

The things addressed in this PR:
- Separates the blog templates into 3 different includes: `_default_blog.html`, `_newsletter.html`, `_special_blog.html`
- Have a dropdown in admin to select the type of blog: Default, Newsletter, Special. This dropdown is in the settings panel. If someone feels it should be somewhere else, let me know.
- Depending on the type selected by the editor, we chose in blog_page.html which of the 3 templates to include.
- Adds SiteSettings for donation page and newsletter subscription page (Used in newsletter templates)
- Adds ButtonBlock in the body of the blog model so that "Related incidents" buttons can be added to the body of the newsletters as shown in the design provided
- Adds filtering by type in the blog index page. This is currently used only in the individual newsletter pages, for the button "Go to archived editions", which filters by `type=newsletter`. But all the other types (`default`, `special` can also be used by updating the GET parameters in the URL
- Adds absolute positioned hero image for the special blog templates (everything else was same as default template). Here, I did take few decisions, so let me know if all these makes sense:
  - I have made the lead image of the blog post as the absolute positioned (full width background image) image
  - while doing the above, I noticed that the `.header` and all our buttons have a white background. This didn't work for this template, so I made them `transparent`, instead of `white`. I checked a bit and didn't seem to break anything, so if anyone knows a reason why this might be problematic, let me know.
  - I added a gradient on top of the image which is darker below, and quite white above. This is my desperate attempt at hoping that in most scenarios, the text on top of the image is accessible, but it will still depend on the editors and the image they select. So might be something to draw attention to the editor. Also, in case someone feels the gradient needs to be adjusted, let me know (attn @harrislapiroff )
  - The author and publication dates are shown on top of this background, and the attribution for the image as well. Since this is a background image, I am not sure what to do with caption. I do want to add a caption, but also, a screen reader user will never encounter the image (just an empty div). I was thinking of adding an `.sr-only`  caption to indicate we do have an image and this is what the image shows. Not sure if there is some other way we should be using the caption.
- The only thing I have skipped in this PR, that I initially mentioned in the issue about implementing is the "In the Database" section. The default template and the special blog template have a "In the Database" section at the bottom of the page in the design. But I was not very clear what incidents we really want to show here. I think this can be implemented as a separate PR as well.
- The special blog template design has some dated sections in the body, I am not really sure if they are supposed to be updates or something else. Right now, the body is just like default blog body. (attn @harrislapiroff )
 
Screenshot of an example newsletter:
![image](https://user-images.githubusercontent.com/9530293/226369359-0e95f42b-049a-42f6-955a-2994b05fe4b8.png)

Screenshot of an example special blog post:
![image](https://user-images.githubusercontent.com/9530293/226369498-4729d0e8-7c52-4725-be04-ab122c2897c5.png)

@chigby I would be interested to know what kind of tests you think I should add for these, since most of them are visual changes. I am however thinking of updating createdevdata to add some newsletter and some special blog templates.

PS: This doesn't add or change how the visualization works in newsletter. It's still treated an image shown exactly how it is in default template.

Another PS: This PR doesn't change the blog index design. Accurat did provide us a fancier design for the index page which changes the layout for special blog listing. I think can be done as a separate PR.

Lastly, the migration of the blog posts to different type either needs to be manual, I think. Though deploying this won't break anything, just all posts will continue to be shown in default template.

2023-03-20 15:06 UTC, chigby commented
Typically I would say visual changes and styles don't really need automated tests. There are some cases where if a django template has a lot of logic, conditionals, or behavior that varies a lot based on the underlying data, then maybe there should be some tests for that. Something like set up data, request page using the test client, then assert that the rendered HTML has certain features. But glancing at this PR it doesn't really seem like that's the case here for most of these templates.

And of course I always support adding representative content to the createdevdata command :slightly_smiling_face:

2023-04-06 18:18 UTC, harrislapiroff requested changes
This looks good. We can continue to refine as we see it used.

Thanks for noting the button bg color change. I think maybe we should add a special case for the transparent buttons. Making all buttons transparent does slightly change the design, e.g., on the homepage where some buttons are on a gray background. (It will also be relevant for buttons on the gray Incidents Database sidebar, though we don't have any there right now that are in Accurat's mockups.)

I'm fine with a `.sr-only` element for image caption. I also would take using an `<img />` element for the header image (that might have some other advantages, like offloading cropping to wagtail, which has knowledge of focus aread) but making it a background image is fine too.

Before merge:

- [x] Update button color back to while
- [x] Make special transparent button for use in special post header
- [x] Add .sr-only caption for images or make header image img elements

Let's also open some tickets after the fact for changes to the blog index page:

- [ ] Add a special preview for special sections
- [ ] Add a UI for looking at posts in a particular category

2023-04-10 13:46 UTC, SaptakS commented
>  Add a special preview for special sections

Not sure what you mean by this. Do you mean the preview in the blog index page as mentioned by Accurat?

> Add a UI for looking at posts in a particular category

Right now, the filter does work, just the UI is same for all categories. Do we have designs for listing of blog posts in separate category?

2023-04-10 14:22 UTC, harrislapiroff commented
> Not sure what you mean by this. Do you mean the preview in the blog index page as mentioned by Accurat?

I think we're talking about the same thing? "Teaser" might have been a better word here. I'm referring to this:

![image](https://user-images.githubusercontent.com/296631/230919952-2487f517-9839-4b88-9b03-f58a940cd541.png)

> Right now, the filter does work, just the UI is same for all categories. Do we have designs for listing of blog posts in separate category?

Yes, Accurat designed this tab set for swapping between them

![image](https://user-images.githubusercontent.com/296631/230920131-b536119e-5854-4b25-be07-eb3f18fe6551.png)

[Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3689-54926&t=q92LFBtIBwAa4rUz-4)

2023-04-10 14:44 UTC, SaptakS commented
Got it. Thanks for clarifying.

2023-04-10 15:25 UTC, SaptakS commented
Updated the PR to include your suggestions. Also created [separate issue](https://github.com/freedomofpress/pressfreedomtracker.us/issues/1617) for the index page related updates.

2023-04-13 14:43 UTC, harrislapiroff approved these changes
Looks generally good. One small fix and then we're good to go!

2023-04-13 14:43 UTC, harrislapiroff commented on blog/templates/blog/blog_page.html
> +
This doesn't actually work, as per the note at the [bottom of the template inheritance docs](https://docs.djangoproject.com/en/4.2/ref/templates/language/#template-inheritance):

> [`{% block %}`](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#std-templatetag-block) tags are evaluated first. That’s why the content of a block is always overridden, regardless of the truthiness of surrounding tags. For example, this template will always override the content of the title block:
>
> ```
> {% if change_title %}
>    {% block title %}Hello!{% endblock title %}
> {% endif %}
> ```

It doesn't cause any visible problems (it's actually fine having transparent buttons on other blog posts as well) but maybe for legibility we should clean it up one way or another.

2023-04-17 07:36 UTC, merged