Update Incident Cards Design
freedomofpress/pressfreedomtracker.us pull request #1604
Opened 2023-03-23 22:42 UTC by dkaoster

closes #1387

2023-03-27 12:27 UTC, SaptakS requested changes
I used to be a huge supporter of the checkbox hack and CSS-only widgets (and have made multiple PRs using that in past), but over the years I have changed that opinion. The checkbox hack for collapsible items has lot of accessibility issues. This article demonstrates some of them: https://adrianroselli.com/2023/03/css-only-widgets-are-inaccessible.html

Instead of using the checkbox hack for a CSS-only implementation, I would propose a progressive enhancement approach. Let's implement the card design such that the "Show More +" link is not shown for non-js users, and the card is expanded for the non-js users always. In the JS code, make the "Show More +" link visible and hide the expanded content, and then implement the toggle using JS. This way, for non-js users, they just always see the entire card, instead of a collapsible card. For users with JS enabled, they get the collapsible experience. Does that make sense?

2023-03-27 17:07 UTC, dkaoster commented
@SaptakS That makes sense, never knew that the checkbox method was bad for accessibility, thanks for the help.

2023-04-03 08:10 UTC, SaptakS requested changes
This PR works great! Tested both JS disabled state and also checked that it doesn't break the other incident card designs such as the database cards. I requested 2 minor changes. Once they are addressed, I think this PR is ready to be merged.

2023-04-03 08:10 UTC, SaptakS commented on client/common/sass/components/_incident-card.sass
> +				margin-left: 1rem
Based on the figma design, I think this should be 0.5rem.

2023-04-03 08:10 UTC, SaptakS commented on client/common/js/collapsibleCard.js
> +				.forEach((buttonText) => { buttonText.innerText = 'Show Less' })
I think we also need to update the toggle  icon from a plus to a cross and vice-versa in the other scenario. Also, do we really need to `querySelectorAll`? I don't think there will ever be a case where there will be more than one "Show more" button, and that way we can avoid the `forEach`?

2023-04-04 11:44 UTC, SaptakS approved these changes

2023-04-04 13:00 UTC, merged