Track Matomo Events on Filter
freedomofpress/pressfreedomtracker.us pull request #1606
Opened 2023-03-28 22:07 UTC by dkaoster

closes #1599

2023-04-03 20:48 UTC, chigby requested changes
This is looking really good, though I did mark a couple places where a variable needs a small change. 

Also, I think adding a call to the `trackMotomoEvent` function in one other place would catch a lot more activity. Specifically any changes to controls happening _within_ the expanded category filter groups. Here's that place: https://github.com/freedomofpress/pressfreedomtracker.us/blob/sidebar-analytics/client/charts/js/components/CategoryFilter.jsx#L126-L132 -- let me know if I should provide more information about this.

2023-04-03 20:48 UTC, chigby commented on client/charts/js/components/TagFilter.jsx
> +							trackMatomoEvent(['Filter', 'Tags', 'Toggle', tag.name])
I think the `tag` variable here is a simple string (rather than an object), so we can just track that value directly. At least, when I test this out by checking and unchecking the tag boxes I'm seeing this function called with `undefined` in that last position.

2023-04-03 20:48 UTC, chigby commented on client/charts/js/components/TagFilter.jsx
> +					trackMatomoEvent(['Filter', 'Tags', 'Select', tag.name])
See above regarding `tag` vs. `tag.name`

2023-04-04 08:20 UTC, SaptakS commented
I just wanted to bring to attention that these changes may need us to update our privacy policy before it is deployed so that users are informed that they are actions are getting tracked. Also, usually a privacy policy change should be informed to the users on their first visit after the change. Right now, I think our privacy policy is more about a web page requests and not related to what we track for users interaction inside a page. Not sure if we have any plans. cc @harrislapiroff

2023-04-25 18:41 UTC, harrislapiroff commented
Checked in with @eloquence on updating our privacy policy—will wait to hear back.

2023-04-26 00:10 UTC, eloquence commented
I agree with Saptak that we should a sentence to the privacy policy (I would think in the "Analytics" section). With recommended language, we can ask Harlo and Trevor to make a separate determination on how to communicate the change.

Right now the policy states:

> FPF's internal analytical logging involves logging, for up to 30 days, two bytes of the IP address, as well as the referrer page, time stamp, page requested, user agent, language header, website visited, and a hash of all of this information. 

What specifically should be added to this list, and what is the intended retention of this data?

2023-05-01 19:30 UTC, eloquence commented
Discussed a bit at Web Sync today, a couple of additional things to note:
- We have two copies, one at https://freedom.press/privacy-policy/ and one at https://pressfreedomtracker.us/privacy-policy/ (securedrop.org links back to freedom.press, and dangerzone.rocks currently does not link to any privacy policy)
- The policy has explicit language regarding notice requirements:

> FPF's Privacy Policy may change from time to time. However, any revised privacy policy will be consistent with FPF's mission. If we make any substantive changes to our policies, we will place notice in our newsletter and post notice of changes on this page.

I would argue in favor of interpreting this as a substantive change, in part because it'll help us go through the proper process at least once.
- Saptak and others are welcome to add further thoughts or proposed language here; I defer to Harris on final language to propose to Harris/Trevor.

2023-05-15 20:45 UTC, harrislapiroff commented
Whoops I missed that the next step here is for me to come up with proposed language for this change. I'll get that this week

2023-07-10 22:33 UTC, harrislapiroff commented
Okay, at long last here is my proposal. Sorry for the long delay on this—I think I was overthinking it:

> FPF's internal analytical logging involves logging, for up to 30 days, two bytes of the IP address, as well as the referrer page, time stamp, page requested, user agent, language header, website visited, **events taken while on the page (such as selecting particular filters or clicking particular buttons),** and a hash of all of this information.

If we wanted to be extra diligent we _could_ keep a list of the events that we record in the policy. Do we think that would be beneficial?

One thing we could do with the privacy policy is just keep a running changelog at the bottom. I think that would fulfill the notice in the policy element and would also be wonderfully transparent.

I _believe_ these events are governed by the same data retention settings as the rest of our matomo data, but I can double check.

2023-07-10 22:36 UTC, harrislapiroff commented
I've converted this back to draf to indicate that we're not ready to merge it until we iron out the privacy policy elements. @eloquence the language above is ready for your review and for kicking to Harlo and Trevor when you think it's ready.

2023-07-11 21:40 UTC, eloquence commented
I think the language you suggested is good. I don't think we need to go into more detail than that, but will discuss w/ Harlo. 

I agree that a changelog in the policy should meet our notice requirement for the policy page itself. However, we also mention the newsletter, so we should (to adhere to that commitment) draft some language for that as well.

I'll make an ad-hoc channel on Slack to discuss this asynchronously.

2023-08-28 18:46 UTC, harrislapiroff commented
We have updated the Privacy Policy across our sites to allow this sort of analytics collection. Unfortunately this PR has gotten somewhat out of date in the meantime, so kicking back to @dkaoster to get it back up to date for merge (Sorry! Thank you!)

2023-08-29 17:39 UTC, dkaoster commented
Added some testing steps, this should be ready for review!

2023-08-30 15:48 UTC, chigby commented
I think this is probably good to go, though I have one question: while doing one final round of testing this out I noticed that on `TextFilter` components, the track event function is called for every time the text input field changes, so if you're typing something you get an update for each keystroke. If that's something we're okay with for launching this feature, that's fine, but it might be nice to put some timer or debouncing logic on that to make the events that are ultimately sent to Matomo less noisy. 

On the other hand, we don't have all that many text filters on the site right now, so it probably won't be a huge problem to go live with that. Let me know what you all think @dkaoster @harrislapiroff

2023-08-30 15:58 UTC, dkaoster commented
@chigby I think debouncing makes a lot of sense, I can go ahead and add that in.

2023-09-05 21:25 UTC, chigby approved these changes

2023-09-05 21:25 UTC, chigby commented
The debouncing seems to work great, and I think the failing prod check will be resolved in #1735.

2023-09-06 18:23 UTC, merged