Vertical Bar Chart
freedomofpress/pressfreedomtracker.us pull request #1614
Opened 2023-04-05 17:34 UTC by dkaoster

closes #1608

2023-04-17 13:35 UTC, SaptakS commented
@chigby @dkaoster there seems to be a merge conflict. Can either of you look into that?

2023-04-17 15:00 UTC, chigby commented
@SaptakS Should be fixed now

2023-04-18 17:30 UTC, harrislapiroff requested changes
A couple changes in the comments to request and one more here:

![image](https://user-images.githubusercontent.com/296631/232856394-4206f88d-6996-47c6-82e2-3837fb2c1014.png)

Can we get some smarter tick mark formatting? I think I'd like to see logic something like this (feel free to suggest alternatives):

1. If all bars are from a single year, use just a month abbreviation, e.g., "Jan"
2. If bars represent months from multiple years, use a month abbreviation, except for replace the first tick and Jan with the year: e.g., for an x-axis spanning oct 22 to sep 23 "2022, Nov, Dec, 2023, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep"
3. I couldn't tell from my testing, but does it switch to breaking down by year instead of month at some point? If not I think we should—maybe when the date range is more than 2 years? And then tick marks will be just the full year, e.g., "2021, 2022, 2023"

Otherwise this looks really good and I'm very excited to present it to our editors! They're gonna love it.

2023-04-18 17:30 UTC, harrislapiroff commented on common/tests/utils.py
> +        return streamfield_data  # json.dumps(streamfield_data)
If we definitely don't need to convert this to JSON, let's remove this comment

2023-04-18 17:30 UTC, harrislapiroff commented on common/blocks.py
> +    title = blocks.CharBlock(required=True)
I think title should be optional and just not be rendered if blank.

2023-04-18 17:30 UTC, harrislapiroff commented on common/blocks.py
> +        'such as screen readers.',
Let's add a little additional guidance here:

> Description for assistive technology users. If the chart is demonstrating a specific trend, try to include that, e.g., "Bar chart showing a decreasing number of assaults over the course of 2023."

(This is just a general idea of the type of guidance I'd like to provide—if you have better phrasing feel free to use it.)

2023-04-18 19:13 UTC, chigby commented
@harrislapiroff @dkaoster Just pushed some changes to this PR that address all of Harris's changes except for the tick marks.

2023-04-19 19:32 UTC, harrislapiroff approved these changes
The updates here look great! Thanks, all! Let's get it in! 😁

2023-04-19 19:40 UTC, harrislapiroff requested changes
Shoot, sorry, kicking the tires a little more, I noticed the chart isn't sufficiently responsive. Can we get some work on the chart for mobile before we merge @dkaoster? If it could have the slider selector the homepage chart has too, that would be cool, but is not a necessity—we can leave that for a future PR.

2023-04-19 20:52 UTC, dkaoster commented
@harrislapiroff that should do it!

2023-04-20 14:04 UTC, harrislapiroff approved these changes
Amazing! ✨

2023-04-20 14:20 UTC, merged