CSV API Performance
freedomofpress/pressfreedomtracker.us pull request #1650
Opened 2023-05-16 20:54 UTC by chigby

This pull request tries to improve the performance of the CSV-formatted API requests. It was inspired by the fact that we are using this API for our data visualizations, and these can be quite slow in production. For example, here's a page with one: https://pressfreedomtracker.us/blog/celebrating-5-years-since-launch-of-the-us-press-freedom-tracker/

It makes a request to the endpoint: https://pressfreedomtracker.us/api/edge/incidents/?format=csv&limit=99999&fields=date,title,url,categories

Of note:
* CSV formatted (I have learned the CSV format is _preferred_ over the JSON format for data visualizations, which was new info for me).
* `limit=99999` implies no pagination, though this is the default behavior for CSV requests
* Only 4 specific fields mentioned: date, title, url, categories
* No filtering

With this in mind, in this PR I have modified how our incident API view works so that (1) the existing functionality is preserved, but (2) in cases where it's possible, we give a faster response time. The insight I'm applying here is that it is less Django Rest Framework (DRF)'s serializer that's slowing us down (we are already using its most performant type of serializer), but Django's serializing of database rows into model instances. So we can improve performance by never doing that, using SQL expressions to generate the data we need, and then calling [`.values()` on our QuerySet](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#values) to avoid Django's models altogether. 

I've done this by creating a parallel set of code that takes effect for a user's requests to the incident API if it meets all of these requirements:
1. The user has asked for CSV format
2. The user has asked for a subset of fields I've enabled, which are mostly either ones that are "simple" values that don't require any type of processing, or ones I've written SQL expressions for that processing. 
3. The user has not requested any filters

These limitations are mostly there in the interest of expediency: I want to get this out there and I don't want to break anything. For each data field, I have to write some code deriving it as a database expression. Requirement 1 allows me to focus on one output format only. Requirement 2 limits how much code has to be written right now, especially when we have a lot of fields and I don't know which ones to prioritize (ideally the ones used in data visualizations across the site, or regularly requested by other API users). Requirement 3 is because I'm not exactly sure how the filters will interact with this method. I want to enable filters eventually, but I'm imagining it will initially have to be only a subset of ones supported (kind of like the home page CSV endpoint has support for date filters only).

All this is to say:

Under this PR, compared to develop, I'm seeing much faster times for requests like:

```
$ time curl -s "http://localhost:8000/api/edge/incidents/?format=csv&limit=9999&fields=title,date,url,categories"
```

(where I have ~1800 incidents in my local db).

And if there are any specific fields or filters we'd like to add before merging this PR, please let me know.

2023-05-16 21:50 UTC, harrislapiroff commented
Nice insights! 

Not sure if this is the PR for it, but the mention of `limit=9999` makes me wonder if we should have an explicit flag for "all incidents" like `limit=0` or `limit=none`.

Looking forward to reviewing the performance gains here.

2023-05-23 21:16 UTC, chigby commented
Pushed a change to allow filters when using the "new" API logic. They didn't have much effect on performance.

2023-05-24 22:20 UTC, harrislapiroff commented
Hm, this is tough, because I could definitely imagine any number of fields being requested for data visualizations. For now let's just draw from the fields we use in existing visualizations. This means we should add:

* city
* state
* longitude
* latitude
* tags

One question: is this the sort of thing where we want to keep the list of supported fields pretty short for performance or is it the sort of thing where we can make it as long as we want it just means writing additional code for each field?

2023-05-25 15:01 UTC, chigby commented
To answer your question: I don't think having more _supported_ fields will affect performance much. I want to get as many supported as possible, but I wanted to start with the highest priority ones.

2023-05-30 14:02 UTC, SaptakS requested changes
Code looks mostly good to me. Left some comments. I also wonder if we can cache the annotations and enabled_filter_set_categories. I don't know how performance intensive operations they are though.

2023-05-30 14:02 UTC, SaptakS commented on incident/api/views.py
> +            return set()
Small knitpick but I think the `else` is not needed since the `if` block has a return statement.
```suggestion
        if fields := self.request.GET.get('fields'):
            return set(map(str.strip, fields.split(',')))
        return set()
```

2023-05-30 14:02 UTC, SaptakS commented on incident/api/views.py
> +                return FlatIncidentSerializer
```suggestion
            if self.can_apply_csv_serializer:
                return CSVIncidentSerializer
            return FlatIncidentSerializer
```

2023-05-30 14:02 UTC, SaptakS commented on incident/api/views.py
> +            return False
```suggestion
        if self.requested_fields:
            return self.requested_fields <= CSVIncidentSerializer().fields.keys()
        return False
```

2023-05-30 14:26 UTC, chigby commented on incident/api/views.py
> +            return set()
Good point, I do like this more

2023-05-31 11:04 UTC, SaptakS approved these changes
I did a code review and looks good to me. I am not sure if there are more fields, etc. that needs to be added, so not merging it. Feel free to merge if you think it's complete.

2023-05-31 20:12 UTC, merged