Add Database Filter Summary
freedomofpress/pressfreedomtracker.us pull request #1727
Opened 2023-08-26 02:23 UTC by dkaoster

## Description

Fixes #1706 

This PR adds the current filters as little pills to the top of the database page, allowing users to clear specific filters by clicking on each pill. 

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Vulnerabilities update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing

- Run the application locally, and test adding some filters on this page: http://localhost:8000/all-incidents/
- The summary should show up above the database entries.
- Ensure that desktop, mobile, and tablet all look good

### Post-deployment actions

In case this PR needs any admin changes or run a management command after deployment, mention it here:

## Checklist

### General checks

- [ ] Linting and tests pass locally
- [ ] The website and the changes are functional in Tor Browser
- [ ] There is no conflicting migrations
- [ ] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [ ] The changes are accessible using keyboard and screenreader

### If you made any frontend change

If the PR involves some visual changes in the frontend, it is recommended to add a screenshot of the new visual.

![Screenshot 2023-08-25 at 4 54 19 PM](https://github.com/freedomofpress/pressfreedomtracker.us/assets/3477162/632a2a1d-625f-4435-a645-88a6d16ec0b8)

2023-08-28 15:54 UTC, SaptakS commented on client/charts/js/components/FilterSummary.jsx
> +						tabIndex={0}
A quick comment before I review the rest of the PR, can we probably add an 
```js
aria-label={`Removes filter: ${category.toLowerCase()}`}
```
or something similar to really convey the intent of the buttons? Because right now it doesn't convey to the user whether clicking the button is going to close th button, or open a new page with the filters or something else.

cc @harrislapiroff in case you have a better idea.

2023-08-28 15:57 UTC, harrislapiroff commented on client/charts/js/components/FilterSummary.jsx
> +						tabIndex={0}
Seems reasonable to me!

2023-09-01 13:48 UTC, SaptakS requested changes
I have left a few changes requested. After that, I think this PR should be ready to be merged.

2023-09-01 13:48 UTC, SaptakS commented on client/charts/js/components/FilterSummary.jsx
> +						tabIndex={0}
There is no need to add `tabIndex=0` on a button I think since it is already interactive.

2023-09-01 13:48 UTC, SaptakS commented on client/charts/js/components/FilterSummary.jsx
> +							"tags", categories.filter(d => d !== tag).join(',')
I think this should be `tags.filter...` ?

2023-09-01 13:48 UTC, SaptakS commented on client/common/sass/components/_filters.sass
> +		margin: 2px 2px 2px 0
Small knitpick but according to the figma, the margin between each element is 8px

2023-09-01 13:53 UTC, SaptakS commented
This is definitely not an issue with this PR, and I am also definitely guilty in doing this, but I feel somewhere along the line, we might have lost track of what components we puts incide `client/charts/js/components` vs `client/common/js/components` (or maybe it's just me not remembering a decision we consciously made). According to me, I feel only the chart related components should be in `clients/charts/`, and all the other components such as FilterSummary, FilterSidebar should be inside `clients/common`. @chigby do you remember if we did this because it would be easier to integrate with the charts? I remember we got some react for the charts to begin with and hence put them inside charts.

Again, this is definitely not a comment on this PR, and probably a refactoring discussion. cc: @harrislapiroff

2023-09-01 13:59 UTC, harrislapiroff commented
Hmmm I think `clients/charts/` only ever existed to give Accurat an isolated area to develop their charts in, so, prior to your comment, my instinct would have been to refactor to move all the js to one directory. If we're finding the distinction helpful though, we could come up with some criteria though. What do you all think?

2023-09-01 14:01 UTC, SaptakS commented
I feel like keeping charts in a separate folder make it easier to discover in the codebase, but definitely don't think it's necessary (especially since we have kind of been using it all in one place and there is no distinction as of now).

2023-09-01 20:38 UTC, dkaoster commented
I also think it could be cool in a future ticket to move to it's own folder, for organization's sake.

2023-09-06 08:02 UTC, SaptakS approved these changes

2023-09-06 08:02 UTC, merged