Migrate to new Docker Compose syntax in README
freedomofpress/pressfreedomtracker.us pull request #1808
Opened 2023-12-05 00:35 UTC by eloquence

## Description
From https://docs.docker.com/compose/install/

> Effective July 2023, Compose V1 stopped receiving updates and is no longer in new Docker Desktop releases. Compose V2 has replaced it and is now integrated into all current Docker Desktop versions. For more information, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate).

From that page:

> Update scripts to use Compose V2 by replacing the hyphen (-) with a space, using docker compose instead of docker-compose.

Our `Makefile` targets already were updated in c4f89bcd9fe52f950b43e3bdadd9d736ced33425 but the README still used the old syntax.

2023-12-05 15:58 UTC, chigby requested changes
We might as well update the `TROUBLESHOOTING.md` document while we're at it.

2023-12-07 01:07 UTC, eloquence commented
Updated the remaining mentions -- not sure the `savedb.sh` script is still used, but if it is it'll surely need the new syntax as well.

2023-12-12 16:09 UTC, chigby approved these changes

2023-12-12 16:09 UTC, merged

2023-12-12 16:09 UTC, chigby commented
I think that the save/restore db scripts are no longer used, having been made mostly obsolete by docker.