Draftail plugin for entering stats by search URL
freedomofpress/pressfreedomtracker.us pull request #962
Opened 2020-09-23 20:59 UTC by chigby

This pull request adds a Draftail extension for [managing a new entity](https://docs.wagtail.io/en/v2.7.1/advanced_topics/customisation/extending_draftail.html#creating-new-entities) that wraps our custom statistics tags.

It works like this:

1. A "Stats" button is added to the Rich Text options
2. Pressing this button opens a dialog box where you can select a "dataset" (corresponding to the particular statistic tag you want) and paste a search URL constructed using the filter UI on the front-end of the PFT site.
3. After inputting this information and clicking "Save," the extension queries a new summary API to get the current value for the statistic. 
4. The resulting number is inserted into the rich text field as a clickable, editable entity. On the back end, this is represented by a statistics tag with the parameters that correspond to the dataset chosen and search parameters from the URL.

Some potential further work:

* Better design of the dialog box and/or the entity's representation in the rich text box
* Limiting which rich text fields this button appears in.
* Smoothing out the UX in other ways 

Refs #957

2021-01-13 16:25 UTC, SaptakS approved these changes
Code,  functionality and tests look good to me. @harrislapiroff if you are okay with the UI/UX, this should be ready to merge I think.

2021-01-20 22:01 UTC, harrislapiroff requested changes
This looks fantastic. One change specified inline and a few other visual changes requested, then let's get it up on staging!

- [x] Modal max with 600px
- [ ] Modal background #FFF
- [ ] Modal border-radius 4px
- [ ] More space between radio buttons and their labels
- [ ] If it’s possible to get better vertical alignment of the buttons and their labels (not shown in the screenshot) do it, but no need to spend more than 5 minutes on it
- [ ] Help text for the URL: “Perform a search on the main site for incidents to include in this statistic and copy the URL here.”  (Maybe even link "main site")

![image](https://user-images.githubusercontent.com/296631/105246241-f4524900-5b40-11eb-900b-20974b6a1218.png)

2021-01-20 22:01 UTC, harrislapiroff commented on tracker/settings/dev.py
> +WEBPACK_LOADER['DEFAULT']['TIMEOUT'] = 15  # noqa: F405
This might need to be a little longer. I couldn't start up on my computer without getting timeout errors. Setting it to `60` worked for me.

2021-01-25 16:58 UTC, chigby commented
@harrislapiroff Should be ready to review again, now

2021-01-26 22:42 UTC, harrislapiroff requested changes
Looks like we need to verify that places we allow stats tags also *parse* them (I don't suppose this can be integrated into the wagtail rich text parsing that handles embeds and images?):

![image](https://user-images.githubusercontent.com/296631/105913791-5f959280-5ffb-11eb-929e-2157bd75a50f.png)

I'm also noticing some very buggy behavior when trying to type after adding a stat that I don't know how to characterize, so here's a gif

![Screen Recording 2021-01-26 at 5 45 21 PM](https://user-images.githubusercontent.com/296631/105916318-b8b2f580-5ffe-11eb-9548-8db10afcf62b.gif)

First the cursor went to the beginning of the field after entering the stats token, next I trued to move it manually to the end of the field but as soon as I typed something the entire field changed to just the stat number twice and the cursor moved back to the start. Very odd!

I also noticed that the modal doesn't seem to validate whether I've selected a radio or not? I'd suggest having it default to "Total" and maybe having it validate if none are selected.

And one last thing that I'll call a stretch goal (don't bother if it will take more than 30m)—there's a noticeable delay between hitting "save" and the modal being dismissed. Could we add a spinner or some other loading indicator during that?

- [x] template-side processing of stats in all necessary locations
- [x] weirdness around typing after entering a stat
- [x] radio button default and maybe validation
- [ ] **stretch goal:** loading indicator

2021-01-27 21:00 UTC, chigby commented
Still kind of perplexed by the typing weirdness. I'm wondering if it's possible that I'm misusing `TooltipEntity` from wagtail? I'm also wondering if it's somehow related to exactly what text is inserted at the `Modifier.replaceText` call, but I've tried a lot of things there and it doesn't really affect the behavior of the textbox in a consistent way, or possibly even affect it at all.

2021-02-01 15:46 UTC, chigby commented
I actually think my latest commit fixed the editing behavior & typing oddness

2021-02-01 20:49 UTC, chigby commented
Added a (simple) loading textual loading indicator when the "Save" button is activated on the modal.

2021-02-03 22:36 UTC, harrislapiroff approved these changes
All the fixes work! Let's get it on staging! And also open a ticket for creating a stat widget for getting this behavior outside of rich text fields.

2021-02-03 22:36 UTC, merged